### ISSUE TITLE
Makefile template should clean trash directory

### ISSUE THREAD

**Issue by Cactusinhand** [chriscool/sharnessify#4]
like this:
```diff
diff --git a/sharness/Makefile b/sharness/Makefile
index 6dbe475..edfe837 100644
--- a/sharness/Makefile
+++ b/sharness/Makefile
@@ -27,6 +27,7 @@ clean: clean-test-results
 clean-test-results:
        @echo "*** $@ ***"
        -rm -rf test-results
+       -rm -rf 'trash directory'.*.sh

 $(T): clean-test-results deps
        @echo "*** $@ ***"

```

**Comment by chriscool** [comment]
Thanks for the report! Could you make it a pull request and explain a bit in the commit message what are the benefits (and the drawbacks if any) of this?

**Comment by Cactusinhand** [comment]
> Thanks for the report! Could you make it a pull request and explain a bit in the commit message what are the benefits (and the drawbacks if any) of this?

Sure, have done :)
